//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mjl.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompensationHistory
    {
        public int HistoryID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string CompensationType { get; set; }
        public Nullable<System.DateTime> ValidityStart { get; set; }
        public Nullable<decimal> CompensationRate { get; set; }
        public Nullable<int> PreparedBy { get; set; }
        public Nullable<System.DateTime> PreparedDate { get; set; }
        public Nullable<int> LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
