//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mjl.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyTimeRecord
    {
        public int RecordID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime RecordDate { get; set; }
        public int SystemEqDate { get; set; }
        public Nullable<System.DateTime> TimeLogIn { get; set; }
        public Nullable<System.DateTime> TimeLogOut { get; set; }
        public int TimeLogType { get; set; }
        public int PreparedBy { get; set; }
        public System.DateTime PreparedDate { get; set; }
        public int LastEditBy { get; set; }
        public System.DateTime LastEditDate { get; set; }
        public string Source { get; set; }
        public bool HasComputedPayslip { get; set; }
        public Nullable<decimal> total_duty_hrs { get; set; }
        public Nullable<decimal> total_overtime_hrs { get; set; }
        public Nullable<decimal> holiday_hrs { get; set; }
        public Nullable<decimal> nigthdiff { get; set; }
        public Nullable<int> lates { get; set; }
        public Nullable<int> undertime { get; set; }
        public Nullable<bool> isHalfDay { get; set; }
    }
}
