//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mjl.Models.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbPayrollEntities : DbContext
    {
        public dbPayrollEntities()
            : base("name=dbPayrollEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BillingAdjustment> BillingAdjustments { get; set; }
        public virtual DbSet<BillingSecurity> BillingSecurities { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyHoliday> CompanyHolidays { get; set; }
        public virtual DbSet<CompensationHistory> CompensationHistories { get; set; }
        public virtual DbSet<DailyTimeRecord> DailyTimeRecords { get; set; }
        public virtual DbSet<employee_master> employee_master { get; set; }
        public virtual DbSet<Employee_Payslip> Employee_Payslip { get; set; }
        public virtual DbSet<Employee_Payslip_Adjustment> Employee_Payslip_Adjustment { get; set; }
        public virtual DbSet<Employee_Payslip_Details> Employee_Payslip_Details { get; set; }
        public virtual DbSet<Employee_Payslip_Government> Employee_Payslip_Government { get; set; }
        public virtual DbSet<Employee_Schedule> Employee_Schedule { get; set; }
        public virtual DbSet<employee_timesheet> employee_timesheet { get; set; }
        public virtual DbSet<EmployeeCharge> EmployeeCharges { get; set; }
        public virtual DbSet<EmployeeDependent> EmployeeDependents { get; set; }
        public virtual DbSet<EmployeeGovernment> EmployeeGovernments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeSpous> EmployeeSpouses { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<SSS_Contribution> SSS_Contribution { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<View_billingAdjustments> View_billingAdjustments { get; set; }
        public virtual DbSet<viewChargeReport> viewChargeReports { get; set; }
        public virtual DbSet<viewCompanyHoliday> viewCompanyHolidays { get; set; }
        public virtual DbSet<viewEmployeeCharge> viewEmployeeCharges { get; set; }
        public virtual DbSet<ViewEmployeeV2> ViewEmployeeV2 { get; set; }
    }
}
