//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mjl.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_timesheet
    {
        public int emp_timesheet_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<System.DateTime> date_from { get; set; }
        public Nullable<System.DateTime> date_to { get; set; }
        public Nullable<int> regular_days { get; set; }
        public Nullable<int> holiday_days { get; set; }
        public Nullable<int> restday_days { get; set; }
        public Nullable<int> absent_days { get; set; }
        public Nullable<decimal> overtime_hours { get; set; }
        public Nullable<decimal> lates { get; set; }
        public Nullable<decimal> undertime { get; set; }
        public string status { get; set; }
        public Nullable<int> prepared_by { get; set; }
        public Nullable<System.DateTime> prepared_date { get; set; }
        public Nullable<int> cancelled_by { get; set; }
        public Nullable<System.DateTime> cancelled_date { get; set; }
        public Nullable<int> lastedit_by { get; set; }
        public Nullable<System.DateTime> lastedit_date { get; set; }
    }
}
