//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mjl.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Schedule
    {
        public int ScheduleID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.TimeSpan> TimeIn { get; set; }
        public Nullable<System.TimeSpan> TimeOut { get; set; }
        public Nullable<int> Restday { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> prepared_by { get; set; }
        public Nullable<System.DateTime> prepared_date { get; set; }
        public Nullable<int> latest_edit_by { get; set; }
        public Nullable<System.DateTime> latest_edit_date { get; set; }
        public Nullable<bool> isOutOverDay { get; set; }
    }
}
