//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mjl.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSpous
    {
        public int id { get; set; }
        public string emp_id { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string lastname { get; set; }
        public Nullable<int> preparedBy { get; set; }
        public Nullable<System.DateTime> preparedDate { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
