//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mjl.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCharge
    {
        public int ChargeID { get; set; }
        public string ChargeName { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> date_from { get; set; }
        public Nullable<System.DateTime> date_to { get; set; }
        public string status { get; set; }
        public Nullable<int> prepared_by { get; set; }
        public Nullable<System.DateTime> prepared_date { get; set; }
        public Nullable<int> lastedit_by { get; set; }
        public Nullable<System.DateTime> lastedit_date { get; set; }
        public Nullable<decimal> ChargeAmount { get; set; }
        public Nullable<int> Released_by { get; set; }
        public Nullable<System.DateTime> Released_date { get; set; }
        public Nullable<int> Cancelled_by { get; set; }
        public Nullable<System.DateTime> Cancelled_date { get; set; }
        public Nullable<int> payslip_adjustment_id { get; set; }
        public Nullable<int> payslip_id { get; set; }
    }
}
