//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mjl.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_master
    {
        public string cust_acct_no { get; set; }
        public int countryid { get; set; }
        public string comp_code { get; set; }
        public int franchise { get; set; }
        public string store_code { get; set; }
        public decimal employee_no { get; set; }
        public string username { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string civil_id_no { get; set; }
        public Nullable<System.DateTime> civil_id_expired { get; set; }
        public string health_card_no { get; set; }
        public Nullable<System.DateTime> health_crd_exp { get; set; }
        public Nullable<int> level { get; set; }
        public string password { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> inac_date { get; set; }
        public Nullable<System.DateTime> act_date { get; set; }
        public string passport { get; set; }
        public Nullable<System.DateTime> passport_expr { get; set; }
        public string address_flat { get; set; }
        public string address_floor { get; set; }
        public string address_censuno { get; set; }
        public string address_buildingno { get; set; }
        public string address_street { get; set; }
        public string address_blockno { get; set; }
        public Nullable<int> address_area { get; set; }
        public Nullable<int> address_city { get; set; }
        public Nullable<int> address_country { get; set; }
        public string origin_address { get; set; }
        public string origin_city { get; set; }
        public Nullable<int> origin_country { get; set; }
        public string first_name_a { get; set; }
        public string middle_name_a { get; set; }
        public string last_name_a { get; set; }
        public string father_name_a { get; set; }
        public string father_last_a { get; set; }
        public Nullable<decimal> salary_rate { get; set; }
        public string address_avenue { get; set; }
        public string dept_code { get; set; }
        public string sect_code { get; set; }
        public byte[] photo { get; set; }
        public Nullable<int> genderid { get; set; }
        public Nullable<int> maritalid { get; set; }
        public Nullable<int> nationalityid { get; set; }
        public Nullable<int> worksched { get; set; }
        public string driverlicense { get; set; }
        public Nullable<System.DateTime> driverexpired { get; set; }
        public Nullable<bool> Contract { get; set; }
        public Nullable<int> noyears { get; set; }
        public Nullable<System.DateTime> contract_expired { get; set; }
        public string residency_no { get; set; }
        public Nullable<System.DateTime> residency_expired { get; set; }
        public Nullable<int> bankid { get; set; }
        public string bank_account_no { get; set; }
        public Nullable<int> Passport_countryid { get; set; }
        public string passport_issuedat { get; set; }
        public Nullable<System.DateTime> datehired { get; set; }
        public Nullable<int> statusid { get; set; }
        public string photo_filename { get; set; }
        public string photo_imagetype { get; set; }
        public string phoneno { get; set; }
        public string mobileno { get; set; }
        public string email { get; set; }
        public string compmobno { get; set; }
        public string compemailadd { get; set; }
        public string shift_code { get; set; }
        public string clientassign { get; set; }
        public Nullable<int> shift_type { get; set; }
        public string birthplace { get; set; }
        public Nullable<int> salary_typeid { get; set; }
        public Nullable<int> salary_periodid { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<int> religionid { get; set; }
        public string spouse { get; set; }
        public string spouse_occupation { get; set; }
        public string fathers_name { get; set; }
        public string fathers_occupation { get; set; }
        public string mothers_name { get; set; }
        public string mothers_occupation { get; set; }
        public string parent_address { get; set; }
        public string skillandlanguage { get; set; }
        public string caseemergency { get; set; }
        public string caseemergencycontact { get; set; }
        public string caseemergencyaddress { get; set; }
        public string sssno { get; set; }
        public string pagibig { get; set; }
        public string philhealth { get; set; }
        public string tinno { get; set; }
        public Nullable<int> probitionary { get; set; }
        public Nullable<int> noofmonths { get; set; }
        public Nullable<System.DateTime> endprob { get; set; }
        public Nullable<decimal> housing { get; set; }
        public Nullable<decimal> transpo { get; set; }
        public Nullable<int> sil { get; set; }
        public Nullable<int> vl { get; set; }
        public Nullable<int> sl { get; set; }
        public Nullable<bool> renewcontract { get; set; }
        public Nullable<int> restday { get; set; }
        public Nullable<decimal> allowance_petrol { get; set; }
        public Nullable<decimal> allowance_telephone { get; set; }
        public Nullable<decimal> allowance_travel { get; set; }
        public Nullable<decimal> allowance_car { get; set; }
        public Nullable<decimal> allowance_job_nature { get; set; }
        public Nullable<decimal> allowance_foods { get; set; }
        public Nullable<decimal> allowance_others { get; set; }
        public Nullable<decimal> cash_bond { get; set; }
        public Nullable<decimal> pagibig_contr { get; set; }
        public Nullable<decimal> philhealth_contr { get; set; }
        public string fingerprintid { get; set; }
        public string security_lisence { get; set; }
        public Nullable<System.DateTime> sl_dateexpire { get; set; }
        public byte[] signaturephoto { get; set; }
        public Nullable<bool> photos { get; set; }
        public Nullable<bool> sss_deduct { get; set; }
        public Nullable<bool> pagibig_deduct { get; set; }
        public Nullable<bool> philhealthdeduct { get; set; }
        public Nullable<decimal> chargefee { get; set; }
        public Nullable<decimal> runningbalance { get; set; }
        public Nullable<decimal> defaulthrswork { get; set; }
        public Nullable<decimal> chargepaydaydeduct { get; set; }
        public Nullable<decimal> sprsdhrsprem { get; set; }
        public Nullable<decimal> defaultothrswork { get; set; }
        public Nullable<decimal> nsdhrswork { get; set; }
        public Nullable<bool> totalhrsworby8 { get; set; }
        public Nullable<decimal> billingfee { get; set; }
        public Nullable<decimal> incentive { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
    }
}
