//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mjl.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDependent
    {
        public long id { get; set; }
        public Nullable<long> emp_id { get; set; }
        public string name { get; set; }
        public string relation { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> preparedBy { get; set; }
        public Nullable<System.DateTime> preparedDate { get; set; }
    }
}
