//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mjl.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSS_Contribution
    {
        public int id { get; set; }
        public Nullable<decimal> start_range { get; set; }
        public Nullable<decimal> end_range { get; set; }
        public Nullable<decimal> monthly_salary_credit { get; set; }
        public Nullable<decimal> social_security_er { get; set; }
        public Nullable<decimal> social_security_ee { get; set; }
        public Nullable<decimal> social_security_total { get; set; }
        public Nullable<decimal> ec_er { get; set; }
        public Nullable<decimal> total_contribution_er { get; set; }
        public Nullable<decimal> total_contribution_ee { get; set; }
        public Nullable<decimal> grand_total_contribution { get; set; }
        public Nullable<decimal> total_contribution { get; set; }
    }
}
