//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mjl.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewEmployeeCharge
    {
        public int ChargeID { get; set; }
        public string ChargeName { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> date_from { get; set; }
        public Nullable<System.DateTime> date_to { get; set; }
        public string status { get; set; }
        public Nullable<int> prepared_by { get; set; }
        public Nullable<System.DateTime> prepared_date { get; set; }
        public Nullable<int> lastedit_by { get; set; }
        public Nullable<System.DateTime> lastedit_date { get; set; }
        public Nullable<decimal> ChargeAmount { get; set; }
        public Nullable<int> Released_by { get; set; }
        public Nullable<System.DateTime> Released_date { get; set; }
        public Nullable<int> Cancelled_by { get; set; }
        public Nullable<System.DateTime> Cancelled_date { get; set; }
        public Nullable<int> payslip_adjustment_id { get; set; }
        public Nullable<int> payslip_id { get; set; }
        public int Expr1 { get; set; }
        public Nullable<int> employee_no { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<System.DateTime> DateHired { get; set; }
        public string Gender { get; set; }
        public string Citizenship { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<int> PreparedBy { get; set; }
        public Nullable<System.DateTime> PreparedDate { get; set; }
        public Nullable<int> LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> company_id { get; set; }
        public string contact_no { get; set; }
        public string birth_place { get; set; }
        public Nullable<bool> probitionary { get; set; }
        public Nullable<int> prob_no_of_months { get; set; }
        public Nullable<System.DateTime> end_probitionary_date { get; set; }
        public string province_address { get; set; }
        public string email { get; set; }
        public string Current_country { get; set; }
        public string MaritalStatus { get; set; }
        public string religion { get; set; }
        public string Current_region { get; set; }
        public string Current_city_municipality { get; set; }
        public string Current_street { get; set; }
        public string Current_barangay { get; set; }
        public string Current_sitio { get; set; }
        public string provincial_country { get; set; }
        public string provincial_region { get; set; }
        public string provincial_city_municipality { get; set; }
        public string provincial_street { get; set; }
        public string provincial_barangay { get; set; }
        public string provincial_sitio { get; set; }
        public Nullable<bool> renew_contract { get; set; }
        public string height { get; set; }
        public string weight { get; set; }
    }
}
