//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mjl.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEmployeeV2
    {
        public int EmployeeID { get; set; }
        public Nullable<int> employee_no { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<System.DateTime> DateHired { get; set; }
        public string Gender { get; set; }
        public string Citizenship { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<int> PreparedBy { get; set; }
        public Nullable<System.DateTime> PreparedDate { get; set; }
        public Nullable<int> LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> company_id { get; set; }
        public string contact_no { get; set; }
        public string birth_place { get; set; }
        public Nullable<bool> probitionary { get; set; }
        public Nullable<int> prob_no_of_months { get; set; }
        public Nullable<System.DateTime> end_probitionary_date { get; set; }
        public string province_address { get; set; }
        public string email { get; set; }
        public string Current_country { get; set; }
        public string MaritalStatus { get; set; }
        public string religion { get; set; }
        public string Current_region { get; set; }
        public string Current_city_municipality { get; set; }
        public string Current_street { get; set; }
        public string Current_barangay { get; set; }
        public string Current_sitio { get; set; }
        public string provincial_country { get; set; }
        public string provincial_region { get; set; }
        public string provincial_city_municipality { get; set; }
        public string provincial_street { get; set; }
        public string provincial_barangay { get; set; }
        public string provincial_sitio { get; set; }
        public Nullable<bool> renew_contract { get; set; }
        public string SSS_Number { get; set; }
        public string PagIbig_Number { get; set; }
        public string PhilHealth_Number { get; set; }
        public string TIN_Number { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public string JobName { get; set; }
        public string JobDescription { get; set; }
        public Nullable<int> Expr2 { get; set; }
        public Nullable<System.DateTime> Expr3 { get; set; }
        public Nullable<int> Expr4 { get; set; }
        public Nullable<System.DateTime> Expr5 { get; set; }
        public Nullable<bool> Expr6 { get; set; }
        public Nullable<int> HistoryID { get; set; }
        public Nullable<int> Expr7 { get; set; }
        public string CompensationType { get; set; }
        public Nullable<System.DateTime> ValidityStart { get; set; }
        public Nullable<decimal> CompensationRate { get; set; }
        public Nullable<int> Expr8 { get; set; }
        public Nullable<System.DateTime> Expr9 { get; set; }
        public Nullable<int> Expr10 { get; set; }
        public Nullable<System.DateTime> Expr11 { get; set; }
        public Nullable<bool> Expr12 { get; set; }
        public Nullable<long> goverment_deduction_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<bool> with_sss { get; set; }
        public string sss_type_deduction { get; set; }
        public Nullable<decimal> sss_amount { get; set; }
        public Nullable<bool> with_philhealth { get; set; }
        public string philhealth_type_deduction { get; set; }
        public Nullable<decimal> philhealth_amount { get; set; }
        public Nullable<bool> with_pagibig { get; set; }
        public string pagibig_type_deduction { get; set; }
        public Nullable<decimal> pagibig_amount { get; set; }
        public Nullable<int> prepared_by { get; set; }
        public Nullable<System.DateTime> prepared_date { get; set; }
        public Nullable<int> last_edit_by { get; set; }
        public Nullable<System.DateTime> last_edit_date { get; set; }
        public Nullable<int> Expr13 { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string owner_name { get; set; }
        public Nullable<decimal> admin_fee { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string contact_number { get; set; }
        public Nullable<int> Expr14 { get; set; }
        public Nullable<System.DateTime> Expr15 { get; set; }
        public Nullable<int> Expr16 { get; set; }
        public Nullable<System.DateTime> Expr17 { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> with_tin { get; set; }
        public string atm_number { get; set; }
        public string height { get; set; }
        public string weight { get; set; }
    }
}
