//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mjl.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewCompanyHoliday
    {
        public int HolidayID { get; set; }
        public string HolidayName { get; set; }
        public string HolidayType { get; set; }
        public Nullable<System.DateTime> HolidayDate { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> prepared_by { get; set; }
        public Nullable<System.DateTime> prepared_date { get; set; }
        public Nullable<int> last_edit_by { get; set; }
        public Nullable<System.DateTime> last_edit_date { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int company_id { get; set; }
        public string name { get; set; }
        public string owner_name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string contact_number { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<System.DateTime> Expr2 { get; set; }
        public Nullable<int> Expr3 { get; set; }
        public Nullable<System.DateTime> Expr4 { get; set; }
        public Nullable<bool> is_active { get; set; }
    }
}
